### ISSUE TITLE
The shadow around the secondaryButtonWidget

### ISSUE THREAD

**Issue by Thurayaa** [Anuj2799/searchbar_animation#5]
I can't seem to remove the shadow around the secondaryButtonWidget, and I don't want to go through downloading the source code  just to remove the shadow. Is there something I missed in the attributes of the widget? 
Other then that thank you for the cool package.

**Comment by anuj-patel-dev** [comment]
Hi @Thurayaa,
You could simply disable the `isOriginalAnimation` by passing `false` to disable DecoratedBoxTransition animation. Otherwise if you want that animation and you just want the outside shadow to disappear then pass `false` in `enableButtonShadow` or if you want both shadows to disappear simply set `false` to perviously mentioned both fields. Also you can set the border colour to any colour you desire by passing the colour to the field `buttonBorderColour` but keep in mind for the buttonborder to work you need to disable `isOriginalAnimation`.
